title: Matt Rogers
description: Watch Matt Write
author:
  - name: Matt Rogers
  - email: codemattr@gmail.com
  - url: https://twitter.com/mattr_

markdown: redcarpet
highlighter: rouge
baseurl: ""

paginate: 5

gems:
  - jemoji
  - jekyll-paginate

version: 2.0.0
github:
  repo: https://www.github.com/mattr-/mattr-.github.com
